// ============================================================
// PREORBIT — Notes Path Mapping
// ============================================================

export const notesPaths: Record<string, any> = {
  'java-dsa': {
    'arrays': () => import('../content/java-dsa/arrays/notes').then(m => m.arraysNotes),
    'strings': () => import('../content/java-dsa/strings/notes').then(m => m.stringsNotes),
    'linked-list': () => import('../content/java-dsa/linked-list/notes').then(m => m.linkedListNotes),
    'stack': () => import('../content/java-dsa/stack/notes').then(m => m.stackNotes),
    'queue': () => import('../content/java-dsa/queue/notes').then(m => m.queueNotes),
    'hashing': () => import('../content/java-dsa/hashing/notes').then(m => m.hashingNotes),
    'recursion': () => import('../content/java-dsa/recursion/notes').then(m => m.recursionNotes),
    'searching': () => import('../content/java-dsa/searching/notes').then(m => m.searchingNotes),
    'sorting': () => import('../content/java-dsa/sorting/notes').then(m => m.sortingNotes),
    'trees': () => import('../content/java-dsa/trees/notes').then(m => m.treesNotes),
    'bst': () => import('../content/java-dsa/bst/notes').then(m => m.bstNotes),
    'heap': () => import('../content/java-dsa/heap/notes').then(m => m.heapNotes),
    'graphs': () => import('../content/java-dsa/graphs/notes').then(m => m.graphsNotes),
    'dynamic-programming': () => import('../content/java-dsa/dynamic-programming/notes').then(m => m.dynamicProgrammingNotes),
  },
  'aptitude': {
    'quantitative': {
      'percentage': () => import('../content/aptitude/quantitative/percentage/notes').then(m => m.percentageNotes),
      'profit-loss': () => import('../content/aptitude/quantitative/profit-loss/notes').then(m => m.profitLossNotes),
      'ratio-proportion': () => import('../content/aptitude/quantitative/ratio-proportion/notes').then(m => m.ratioProportionNotes),
      'average': () => import('../content/aptitude/quantitative/average/notes').then(m => m.averageNotes),
      'time-work': () => import('../content/aptitude/quantitative/time-work/notes').then(m => m.timeWorkNotes),
      'time-speed-distance': () => import('../content/aptitude/quantitative/time-speed-distance/notes').then(m => m.timeSpeedDistanceNotes),
      'simple-interest': () => import('../content/aptitude/quantitative/simple-interest/notes').then(m => m.simpleInterestNotes),
      'compound-interest': () => import('../content/aptitude/quantitative/compound-interest/notes').then(m => m.compoundInterestNotes),
      'probability': () => import('../content/aptitude/quantitative/probability/notes').then(m => m.probabilityNotes),
    },
    'logical-reasoning': {
      'coding-decoding': () => import('../content/aptitude/logical-reasoning/coding-decoding/notes').then(m => m.codingDecodingNotes),
      'blood-relations': () => import('../content/aptitude/logical-reasoning/blood-relations/notes').then(m => m.bloodRelationsNotes),
      'direction-sense': () => import('../content/aptitude/logical-reasoning/direction-sense/notes').then(m => m.directionSenseNotes),
      'syllogism': () => import('../content/aptitude/logical-reasoning/syllogism/notes').then(m => m.syllogismNotes),
      'venn-diagrams': () => import('../content/aptitude/logical-reasoning/venn-diagrams/notes').then(m => m.notes),
      'clocks-and-calendars': () => import('../content/aptitude/logical-reasoning/clocks-and-calendars/notes').then(m => m.notes),
      'analogy': () => import('../content/aptitude/logical-reasoning/analogy/notes').then(m => m.analogyNotes),
      'classification': () => import('../content/aptitude/logical-reasoning/classification/notes').then(m => m.classificationNotes),
      'series': () => import('../content/aptitude/logical-reasoning/series/notes').then(m => m.seriesNotes),
      'seating-arrangement': () => import('../content/aptitude/logical-reasoning/seating-arrangement/notes').then(m => m.seatingArrangementNotes),
    },
  },
  'core-cs': {
    'computer-networks': {
      'application-layer': () => import('../content/core-cs/computer-networks/application-layer/notes').then(m => m.notes),
      'dns': () => import('../content/core-cs/computer-networks/dns/notes').then(m => m.notes),
      'http-https': () => import('../content/core-cs/computer-networks/http-https/notes').then(m => m.notes),
      'introduction': () => import('../content/core-cs/computer-networks/introduction/notes').then(m => m.notes),
      'introduction-to-networks': () => import('../content/core-cs/computer-networks/introduction-to-networks/notes').then(m => m.notes),
      'ip-addressing': () => import('../content/core-cs/computer-networks/ip-addressing/notes').then(m => m.notes),
      'network-devices': () => import('../content/core-cs/computer-networks/network-devices/notes').then(m => m.notes),
      'osi-model': () => import('../content/core-cs/computer-networks/osi-model/notes').then(m => m.notes),
      'routing': () => import('../content/core-cs/computer-networks/routing/notes').then(m => m.notes),
      'subnetting': () => import('../content/core-cs/computer-networks/subnetting/notes').then(m => m.notes),
      'tcp': () => import('../content/core-cs/computer-networks/tcp/notes').then(m => m.notes),
      'tcp-ip': () => import('../content/core-cs/computer-networks/tcp-ip/notes').then(m => m.notes),
      'tcp-ip-model': () => import('../content/core-cs/computer-networks/tcp-ip-model/notes').then(m => m.notes),
      'udp': () => import('../content/core-cs/computer-networks/udp/notes').then(m => m.notes),
    },
    'dbms': {
      'concurrency-control': () => import('../content/core-cs/dbms/concurrency-control/notes').then(m => m.notes),
      'database-security': () => import('../content/core-cs/dbms/database-security/notes').then(m => m.notes),
      'er-model': () => import('../content/core-cs/dbms/er-model/notes').then(m => m.notes),
      'indexing': () => import('../content/core-cs/dbms/indexing/notes').then(m => m.notes),
      'introduction': () => import('../content/core-cs/dbms/introduction/notes').then(m => m.notes),
      'introduction-to-dbms': () => import('../content/core-cs/dbms/introduction-to-dbms/notes').then(m => m.notes),
      'keys': () => import('../content/core-cs/dbms/keys/notes').then(m => m.notes),
      'normalization': () => import('../content/core-cs/dbms/normalization/notes').then(m => m.notes),
      'relational-model': () => import('../content/core-cs/dbms/relational-model/notes').then(m => m.notes),
      'sql-basics': () => import('../content/core-cs/dbms/sql-basics/notes').then(m => m.notes),
      'transactions': () => import('../content/core-cs/dbms/transactions/notes').then(m => m.notes),
    },
    'oop': {
      'abstraction': () => import('../content/core-cs/oop/abstraction/notes').then(m => m.notes),
      'classes-and-objects': () => import('../content/core-cs/oop/classes-and-objects/notes').then(m => m.notes),
      'classes-objects': () => import('../content/core-cs/oop/classes-objects/notes').then(m => m.notes),
      'constructors': () => import('../content/core-cs/oop/constructors/notes').then(m => m.notes),
      'encapsulation': () => import('../content/core-cs/oop/encapsulation/notes').then(m => m.notes),
      'exception-handling': () => import('../content/core-cs/oop/exception-handling/notes').then(m => m.notes),
      'inheritance': () => import('../content/core-cs/oop/inheritance/notes').then(m => m.notes),
      'interfaces': () => import('../content/core-cs/oop/interfaces/notes').then(m => m.notes),
      'introduction': () => import('../content/core-cs/oop/introduction/notes').then(m => m.notes),
      'introduction-to-oop': () => import('../content/core-cs/oop/introduction-to-oop/notes').then(m => m.notes),
      'polymorphism': () => import('../content/core-cs/oop/polymorphism/notes').then(m => m.notes),
    },
    'operating-system': {
      'concurrency': () => import('../content/core-cs/operating-system/concurrency/notes').then(m => m.notes),
      'cpu-scheduling': () => import('../content/core-cs/operating-system/cpu-scheduling/notes').then(m => m.notes),
      'deadlocks': () => import('../content/core-cs/operating-system/deadlocks/notes').then(m => m.notes),
      'file-systems': () => import('../content/core-cs/operating-system/file-systems/notes').then(m => m.notes),
      'introduction': () => import('../content/core-cs/operating-system/introduction/notes').then(m => m.notes),
      'introduction-to-os': () => import('../content/core-cs/operating-system/introduction-to-os/notes').then(m => m.notes),
      'memory-management': () => import('../content/core-cs/operating-system/memory-management/notes').then(m => m.notes),
      'process-management': () => import('../content/core-cs/operating-system/process-management/notes').then(m => m.notes),
      'synchronization': () => import('../content/core-cs/operating-system/synchronization/notes').then(m => m.notes),
      'threads': () => import('../content/core-cs/operating-system/threads/notes').then(m => m.notes),
      'virtual-memory': () => import('../content/core-cs/operating-system/virtual-memory/notes').then(m => m.notes),
    },
    'sql': {
      'aggregate-functions': () => import('../content/core-cs/sql/aggregate-functions/notes').then(m => m.notes),
      'constraints': () => import('../content/core-cs/sql/constraints/notes').then(m => m.notes),
      'dcl': () => import('../content/core-cs/sql/dcl/notes').then(m => m.notes),
      'ddl': () => import('../content/core-cs/sql/ddl/notes').then(m => m.notes),
      'dml': () => import('../content/core-cs/sql/dml/notes').then(m => m.notes),
      'dql': () => import('../content/core-cs/sql/dql/notes').then(m => m.notes),
      'group-by': () => import('../content/core-cs/sql/group-by/notes').then(m => m.notes),
      'having': () => import('../content/core-cs/sql/having/notes').then(m => m.notes),
      'indexing': () => import('../content/core-cs/sql/indexing/notes').then(m => m.notes),
      'introduction': () => import('../content/core-cs/sql/introduction/notes').then(m => m.notes),
      'joins': () => import('../content/core-cs/sql/joins/notes').then(m => m.notes),
      'queries': () => import('../content/core-cs/sql/queries/notes').then(m => m.notes),
      'select': () => import('../content/core-cs/sql/select/notes').then(m => m.notes),
      'sql-introduction': () => import('../content/core-cs/sql/sql-introduction/notes').then(m => m.notes),
      'subqueries': () => import('../content/core-cs/sql/subqueries/notes').then(m => m.notes),
      'tcl': () => import('../content/core-cs/sql/tcl/notes').then(m => m.notes),
      'where': () => import('../content/core-cs/sql/where/notes').then(m => m.notes),
    },
  },
};
